language: php

php:
  - 5.6
  - 7.0 

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
    - composer install

after_script:
  - php vendor/bin/coveralls

notifications:
  email:
    - jose.gilmolina@gmail.com
